services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    networks:
      - app-network
    # Healthcheck to ensure the database is ready before the app starts
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-psecret",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  task-tracker-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-tracker-backend
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - MARIADB_USER=user
      - MARIADB_PASSWORD=mysecretpw
      - APP_JWT_SECRET=6d6319eb8e676a989ee3932b5cc9e916e2125fdc97a3d2db500eab6d63822812
      # The hostname 'mariadb' comes from the name of the database service above
      - DATABASE_HOST=mariadb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
